In [62]:
from train_classifieur import train_classifier, pred_classifier
import utils 
import os
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import plotly.express as px
import plotly.graph_objects as go
import subprocess


utils.load_env_file()
data_dir = os.getenv("DATA_DIR", "data/default/")
print(data_dir)

../LALAOUI_RAYAN/selected_data

In [63]:
def reset_weights():
    csv_df = pd.read_csv(data_dir + "/metadata.csv")
    csv_df.iloc[:, -1] = 1  
    csv_df.to_csv(data_dir + "/metadata.csv", index=False)

reset_weights()
#result = subprocess.run(["./train_classifieur.sh"], capture_output=True, text=True)

In [64]:
from sklearn.preprocessing import MultiLabelBinarizer

df = pd.read_csv(data_dir+"/metadata.csv")
mlb = MultiLabelBinarizer()
one_hot = df["Finding Labels"].str.get_dummies(sep="|")
df = pd.concat([df.drop(columns="Finding Labels"), one_hot] , axis=1 )
#Suppression des outliers
print(df[df["Patient Age"] > utils.MAX_AGE].shape)
df = df[df["Patient Age"] <= utils.MAX_AGE]
original_columns = list(df.columns)
original_df = df.copy()
df

(0, 26)

,Image Index,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],...,Emphysema,Fibrosis,Hernia,Infiltration,Mass,No Finding,Nodule,Pleural_Thickening,Pneumonia,Pneumothorax
0,00000001_000.png,0,1,58,M,PA,2682,2749,0.143000,0.143000,...,0,0,0,0,0,0,0,0,0,0
1,00000005_006.png,6,5,70,F,PA,2992,2991,0.143000,0.143000,...,0,0,0,1,0,0,0,0,0,0
2,00000014_000.png,0,14,61,F,PA,2048,2500,0.171000,0.171000,...,0,0,0,0,0,1,0,0,0,0
3,00000048_000.png,0,48,46,F,PA,2834,2641,0.143000,0.143000,...,0,0,0,0,0,1,0,0,0,0
4,00000051_000.png,0,51,55,M,PA,3056,2544,0.139000,0.139000,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,00030633_000.png,0,30633,50,F,PA,2021,2021,0.194311,0.194311,...,0,0,0,1,0,0,0,0,0,0
1496,00030681_000.png,0,30681,39,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,0,0,1,0,0,0,0
1497,00030683_000.png,0,30683,43,M,AP,3056,2544,0.139000,0.139000,...,0,0,0,0,0,0,0,0,0,0
1498,00030759_000.png,0,30759,51,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,0,0,0,0,0,0,0
1499,00030796_000.png,0,30796,44,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,0,0,1,0,0,0,0

# Analyse Descriptive

## Analyse Univarié
On s'interesse ici d'abord au sexe:

In [65]:

def print_sex_count(df):
    gender_counts = df["Patient Gender"].value_counts()
    print(f"Il y a : {gender_counts.get(0, None)} hommes et {gender_counts.get(1, None)} femmes")

    gender_counts = df["Patient Gender"].value_counts(normalize=True)
    print(f"Soit {gender_counts.get(0, None):.2%} d'hommes et {gender_counts.get(1, None):.2%} de femmes")
print_sex_count(df)

px.pie(df, 'Patient Gender')

Il y a : 802 hommes et 698 femmes
Soit 53.47% d'hommes et 46.53% de femmes

/tmp/ipykernel_3160/3576762671.py:3: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/tmp/ipykernel_3160/3576762671.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

puis à l'âge:

In [66]:
print(pd.cut(df["Patient Age"], [0,30,60,utils.MAX_AGE], labels=["jeunes", "adultes", "seniors"]).value_counts())
utils.plot_age_dist(df, vlines=[30,60])

Patient Age
adultes    894
jeunes     315
seniors    291
Name: count, dtype: int64

Enfin à la distribution des maladies:

In [67]:
utils.trace_effectif_maladie(df, gender=False)

In [68]:
print("------- Count -------")
print(df[utils.maladies].sum(axis=0).sort_values(ascending=False))
print("------- Moyennes -------")
print(df[utils.maladies].mean().sort_values(ascending=False))

------- Count -------
No Finding            809
Infiltration          270
Atelectasis           126
Effusion              101
Nodule                 97
Mass                   80
Pleural_Thickening     48
Cardiomegaly           40
Fibrosis               36
Consolidation          34
Pneumothorax           30
Emphysema              21
Pneumonia              20
Edema                  14
Hernia                  8
dtype: int64
------- Moyennes -------
No Finding            0.539333
Infiltration          0.180000
Atelectasis           0.084000
Effusion              0.067333
Nodule                0.064667
Mass                  0.053333
Pleural_Thickening    0.032000
Cardiomegaly          0.026667
Fibrosis              0.024000
Consolidation         0.022667
Pneumothorax          0.020000
Emphysema             0.014000
Pneumonia             0.013333
Edema                 0.009333
Hernia                0.005333
dtype: float64

In [69]:

jaccard_matrix = np.zeros((len(utils.maladies), len(utils.maladies)))
for i, disease1 in enumerate(utils.maladies):
    for j, disease2 in enumerate(utils.maladies):
        intersection = np.logical_and(df[disease1], df[disease2]).sum()
        union = np.logical_or(df[disease1], df[disease2]).sum()
        jaccard_matrix[i, j] = intersection / union if union != 0 else 0

jaccard_df = pd.DataFrame(jaccard_matrix, index=utils.maladies, columns=utils.maladies)

fig = go.Figure(data=go.Heatmap(
    z=jaccard_df.values,
    x=jaccard_df.columns,
    y=jaccard_df.index,
    colorscale='Blues'
))

fig.update_layout(title='Disease Co-Occurrence Matrix (Jaccard Distance)',
                  xaxis_title='Disease',
                  yaxis_title='Disease',
                  xaxis=dict(tickangle=-45),
                  width=800, height=800)

fig.show()

## Analyse Bivarié

On a vu durant le mi-projet que les colonnes: `View Position ,OriginalImage[Width ,Height]	,OriginalImagePixelSpacing[x,	y]` ne contiennent pas de biais significatifs , on se concentrera dans la suite sur l'âge et le sexe.

Essayons d'abord de visualiser la distribution d'un attribut par rapport à l'autre.

In [70]:
utils.plot_age_dist(df, gender=True)

## Analyse de l'influence du sexe sur les labels:

In [71]:
utils.trace_effectif_maladie(df, gender=True)

## Passons à l'âge:

In [72]:
utils.plot_avg_diseases_by_age(df, maladies=utils.onlymaladies, window_size=5, vlines=[40])
utils.plot_avg_diseases_by_age(df, maladies=utils.onlymaladies, vlines=[40], gender=True)

In [73]:

def plot_age_histogram(df):
    bins = list(range(0, df["Patient Age"].max() + 20, 20)) 
    labels = [f"{bins[i]}-{bins[i+1]-1}" for i in range(len(bins)-1)]  
    df["Age Group"] = pd.cut(df["Patient Age"], bins=bins, labels=labels, right=False)
    fig = px.bar(df["Age Group"].value_counts().sort_index(),
                 x=df["Age Group"].unique(),
                 y=df["Age Group"].value_counts(),
                 title="Répartition des patients par tranche d'âge",
                 labels={"x": "Tranche d'âge", "y": "Nombre de patients"},
                 color=df["Age Group"].unique(),
                 color_discrete_sequence=px.colors.qualitative.Set3) 

    fig.update_layout(xaxis_title="Tranche d'âge", yaxis_title="Nombre de patients")
    fig.show()


plot_age_histogram(df)

In [74]:
utils.plot_disease_trends(df, "No Finding", gender=False)
utils.plot_disease_trends(df, utils.onlymaladies, gender=False)

In [75]:
utils.plot_patient_age_distribution(df)

In [76]:
utils.plot_disease_trends(df, utils.maladies, gender=True)
utils.stacked_area_chart(df, maladies=utils.onlymaladies, gender=True)

## Zoom sur les images:
La nouveauté par rapport au mi-projet c'est l'ajout des images au dataset, ces nouvelles données pourrait introduire de nouveaux biais comme une faible luminosité, la présence de dispositif intra-corporelle etc.

In [77]:
from PIL import Image
import image_utils
from pathlib import Path



def load_images_from_directory(directory_path):
    # Initialize empty lists to store image objects and their names
    image_objects = []
    image_names = []

    # Use Path to recursively find all image files in the directory and subdirectories
    image_extensions = {".png", ".jpg", ".jpeg", ".bmp", ".gif"}
    for img_path in Path(directory_path).rglob("*"):
        if img_path.suffix.lower() in image_extensions:
            # Open image and store the image object
            img = Image.open(img_path)
            image_objects.append(img)
            
            # Store the image file name
            image_names.append(img_path.name)
    
    # Create a DataFrame with image objects and their names
    df = pd.DataFrame({
        'image': image_objects,
        'file_name': image_names
    })
    
    return df

images_df = load_images_from_directory(data_dir)
images = images_df["image"]

N=6
image_utils.display_images(images.loc[:N-1])

On remarque la présence de pictogram visuels liée au metadonnées qui parfois se supperpose aux images.

In [78]:
filtered_imgs = [image_utils.transparent_background(img, ~image_utils.foreground_filter(img)) for img in images[:N] ]
image_utils.display_images(filtered_imgs)

In [79]:
def lightness(img: Image.Image) -> float:
    """Return the darkness of a PIL image."""
    M = np.array(img)
    G = M[:, :, 1] * 1.0
    R = M[:, :, 0] * 1.0
    B = M[:, :, 2] * 1.0
    gris = (R + G + B) / 3
    M = [
        [[gris[i][j] for k in range(3)] for j in range(len(M[i]))]
        for i in range(len(M))
    ]
    F = image_utils.foreground_filter(M, 130)
    return np.mean(gris[F])

""" lightness_metric = pd.DataFrame([lightness(img) for img in images], columns=["lightness"])
images_df["lightness"] = lightness_metric
images_df = images_df.drop(columns=["image"])
images_df.to_csv("lightness.csv", index=False) """
lightness_metric = pd.read_csv("./lightness.csv")
lightness_metric = lightness_metric.rename(columns={"file_name" : "Image Index"})
lightness_metric

           Image Index  lightness
0     00029210_000.png  77.073721
1     00029643_000.png  76.790874
2     00011500_000.png  66.018137
3     00002617_000.png  71.700541
4     00018772_000.png  64.387512
...                ...        ...
1495  00011810_000.png  70.876629
1496  00025124_003.png  69.104207
1497  00023629_004.png  59.802403
1498  00030078_000.png  88.036470
1499  00009303_000.png  60.651203

[1500 rows x 2 columns]

In [80]:
print(lightness_metric['lightness'].describe(include=all))
fig = go.Figure(data=go.Box(y=lightness_metric["lightness"], name="Lightness"))
fig.update_layout(
    title="Lightness",
    yaxis_title="Values",
)
fig.show()

count    1500.000000
mean       72.938384
std        14.437157
min        15.075729
25%        63.479997
50%        70.741514
75%        83.213571
max       109.922028
Name: lightness, dtype: float64

In [81]:
df = pd.merge(df, lightness_metric, on="Image Index")
df

,Image Index,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],...,Hernia,Infiltration,Mass,No Finding,Nodule,Pleural_Thickening,Pneumonia,Pneumothorax,Age Group,lightness
0,00000001_000.png,0,1,58,M,PA,2682,2749,0.143000,0.143000,...,0,0,0,0,0,0,0,0,40-59,67.919649
1,00000005_006.png,6,5,70,F,PA,2992,2991,0.143000,0.143000,...,0,1,0,0,0,0,0,0,60-79,52.914027
2,00000014_000.png,0,14,61,F,PA,2048,2500,0.171000,0.171000,...,0,0,0,1,0,0,0,0,60-79,73.978926
3,00000048_000.png,0,48,46,F,PA,2834,2641,0.143000,0.143000,...,0,0,0,1,0,0,0,0,40-59,64.454487
4,00000051_000.png,0,51,55,M,PA,3056,2544,0.139000,0.139000,...,0,1,0,0,0,0,0,0,40-59,71.254098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,00030633_000.png,0,30633,50,F,PA,2021,2021,0.194311,0.194311,...,0,1,0,0,0,0,0,0,40-59,93.543533
1496,00030681_000.png,0,30681,39,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,1,0,0,0,0,20-39,94.068207
1497,00030683_000.png,0,30683,43,M,AP,3056,2544,0.139000,0.139000,...,0,0,0,0,0,0,0,0,40-59,92.758716
1498,00030759_000.png,0,30759,51,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,0,0,0,0,0,40-59,99.808464
1499,00030796_000.png,0,30796,44,M,PA,2021,2021,0.194311,0.194311,...,0,0,0,1,0,0,0,0,40-59,94.265348

In [82]:
#On met la colonne lightness en metadata et on train dessus pour savoir si elle influe vraiment
#df.to_csv("../LALAOUI_RAYAN/selected_data/metadata_with_lightness.csv", index=False)

- Introduction (/3)
- Preparation et analyse des données (/3)
- Application des méthodes de pre processing (/5)
- Application des méthodes de post processing (/5)
- Analyse, compréhension (/3)
- Conclusion (/1)

In [83]:
# Charger le DataFrame
preddf = pd.read_csv("expe_log/base_preds.csv")

# Nettoyer les espaces dans les noms de colonnes
preddf.columns = preddf.columns.str.strip()

y_pred = preddf["preds"]
y_true = preddf["labels"]
y_pred = y_pred.map({"sain": 0, "malade": 1})
y_true = y_true.map({"sain": 0, "malade": 1})

preddf_lightness = pd.read_csv("expe_log/preds_with_lightness.csv")
preddf_lightness.columns = preddf_lightness.columns.str.strip()
y_pred_lightness = preddf_lightness["preds"]
y_pred_lightness = y_pred_lightness.map({"sain": 0, "malade": 1})

abs((y_pred_lightness - y_true)/y_true.size).sum() , abs((y_pred - y_true)/y_true.size).sum()

(np.float64(0.30600000000000005), np.float64(0.22333333333333333))

In [84]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np

def display_error_rate(y_true, y_pred, df, group_columns):
    for group_value, group_df in df.groupby(group_columns):
        y_true_group = y_true[group_df.index]
        y_pred_group = y_pred[group_df.index]
        
        cm = confusion_matrix(y_true_group, y_pred_group)    
    
        total = cm.sum()
        correct = np.trace(cm) 
        error_rate = (total - correct) / total * 100 
        
        print(f"Taux d'erreur pour le groupe {group_columns}: {group_value} = {error_rate:.2f}%")

display_error_rate(y_true, y_pred, preddf, group_columns=["Patient Gender"])
preddf['+40ans']=preddf['Patient Age'] >= 40
display_error_rate(y_true, y_pred, preddf, group_columns=["+40ans"])

Taux d'erreur pour le groupe ['Patient Gender']: ('F',) = 20.77%
Taux d'erreur pour le groupe ['Patient Gender']: ('M',) = 23.69%
Taux d'erreur pour le groupe ['+40ans']: (False,) = 16.02%
Taux d'erreur pour le groupe ['+40ans']: (True,) = 25.66%

In [85]:
import pandas as pd
import plotly.express as px
from sklearn.metrics import confusion_matrix
import numpy as np

def plot_confusion_matrix(y_true, y_pred, labels=["sain", "malade"], normalize=False, title="Matrice de Confusion"):
    cm = confusion_matrix(y_true, y_pred)
    
    if normalize:
        cm = cm.astype('float') / len(y_true) * 100
    
    cm_df = pd.DataFrame(cm, index=labels, columns=labels)
    
    fig = px.imshow(cm_df, 
                    labels=dict(x="Prédiction", y="Vérité", color="Fréquence (%)" if normalize else "Fréquence"), 
                    x=labels, 
                    y=labels, 
                    color_continuous_scale='Blues',
                    range_color=[0, 100] if normalize else None) 
    
    for i in range(len(cm_df)):
        for j in range(len(cm_df.columns)):
            fig.add_annotation(
                x=j,
                y=i,
                text=f'{cm_df.iloc[i, j]:.2f}%' if normalize else f'{cm_df.iloc[i, j]}',
                showarrow=False,
                font=dict(color="black", size=14),
                align="center"
            )
    
    fig.update_layout(title=title, xaxis_title="Prédiction", yaxis_title="Vérité")
    fig.show()

In [86]:
plot_confusion_matrix(y_true, y_pred, normalize=True)
plot_confusion_matrix(y_true, y_pred)

Oula il predit a tendence a se tromper sur de faux negatif, ce n'est pas ce qu'on veut !!!

In [87]:
def plot_confusion_matrix_by_group(y_true, y_pred, df, group_columns, labels=None, normalize=False):
    """
    Affiche des matrices de confusion séparées pour chaque groupe défini par group_columns.
    """
    for group_value, group_df in df.groupby(group_columns):
        y_true_group = y_true[group_df.index]
        y_pred_group = y_pred[group_df.index]
        
        print(f"Matrice de confusion pour {group_columns}: {group_value}")
        plot_confusion_matrix(y_true_group, y_pred_group, labels, normalize, title=f"Matrice de Confusion ({group_columns}={group_value})")

In [88]:
preddf['+40ans'] = preddf['Patient Age'] >= 40
plot_confusion_matrix_by_group(y_true, y_pred, preddf, group_columns=["+40ans"], labels=["sain", "malade"])

Matrice de confusion pour ['+40ans']: (False,)

Matrice de confusion pour ['+40ans']: (True,)

# PreProc
## Reweighing

In [89]:
import os

# Define paths to the train repository
train_sain_path = data_dir+"/train/sain"
train_malade_path = data_dir+"/train/malade"

# Get the list of image filenames in the train repository
train_images = set(os.listdir(train_sain_path) + os.listdir(train_malade_path))


def convert_to_all_numerical(preddf):
    preddf.columns = preddf.columns.str.strip()
    preddf["in_train"] = preddf["Image Index"].apply(lambda x: 1 if x in train_images else 0)
    
    if not pd.api.types.is_numeric_dtype(preddf["preds"]):
        preddf["preds"] = preddf["preds"].map({"sain": 0, "malade": 1}) 
    if not pd.api.types.is_numeric_dtype(preddf["labels"]):
        preddf["labels"] = preddf["labels"].map({"sain": 0, "malade": 1})
    if not pd.api.types.is_numeric_dtype(preddf["Patient Gender"]):
        preddf["Patient Gender"] = preddf["Patient Gender"].map({"M": 0, "F": 1})
    if "View Position" in preddf.columns and not pd.api.types.is_numeric_dtype(preddf["View Position"]):
        preddf["View Position"] = preddf["View Position"].map({"AP": 0, "PA": 1})
    if "+40ans" not in preddf.columns:
        preddf["+40ans"] = (preddf["Patient Age"] > 40).astype(int) 
    return preddf

In [90]:
#On numérise toutes les colonnes
import pandas as pd
from aif360.datasets import BinaryLabelDataset

preddf = pd.read_csv("expe_log/preds.csv")
preddf = convert_to_all_numerical(preddf)


protected_attributes = ['Patient Gender', '+40ans']

protected_attribute = protected_attributes[1]
priviliged_group = 0
unpriviliged_group = 1

label = 'Finding Labels'
df_ohe = preddf[label].str.get_dummies(sep='|').astype(bool)
preddf = preddf.drop(columns=['Finding Labels']).join(df_ohe)

filtered_df = preddf.drop(["View Position", "Finding Labels", "Image Index"], axis=1, errors="ignore")

if protected_attribute in list(filtered_df.columns):
    dataset = BinaryLabelDataset(
        favorable_label=0,  # "Sain" est la classe favorable
        unfavorable_label=1,  # "Malade" est la classe défavorable
        df=filtered_df,
        label_names=["labels"],
        protected_attribute_names=[protected_attribute]
    )

    t = filtered_df[filtered_df["in_train"]==1].copy().reset_index()
    train_dataset = BinaryLabelDataset(
        favorable_label=0,  # "Sain" est la classe favorable
        unfavorable_label=1,  # "Malade" est la classe défavorable
        df=t,
        label_names=["labels"],
        protected_attribute_names=[protected_attribute]
    )


    d = filtered_df[filtered_df["in_train"]==0].copy().reset_index()
    test_dataset = BinaryLabelDataset(
        favorable_label=0,  # "Sain" est la classe favorable
        unfavorable_label=1,  # "Malade" est la classe défavorable
        df=d,
        label_names=["labels"],
        protected_attribute_names=[protected_attribute]
    )

else:
    print(f"Colonne protégée '{protected_attribute}' non trouvée dans le dataset.")


dataset

               instance weights    features                         \

                                Follow-up # Patient ID Patient Age
instance names
0                           1.0         0.0        1.0        58.0
1                           1.0         6.0        5.0        70.0
2                           1.0         0.0       14.0        61.0
3                           1.0         0.0       48.0        46.0
4                           1.0         0.0       51.0        55.0
...                         ...         ...        ...         ...
1495                        1.0         0.0    30633.0        50.0
1496                        1.0         0.0    30681.0        39.0
1497                        1.0         0.0    30683.0        43.0
1498                        1.0         0.0    30759.0        51.0
1499                        1.0         0.0    30796.0        44.0

                                                           \

               Patient Gender OriginalImage[Width Height]
instance names
0                         0.0              2682.0  2749.0
1                         1.0              2992.0  2991.0
2                         1.0              2048.0  2500.0
3                         1.0              2834.0  2641.0
4                         0.0              3056.0  2544.0
...                       ...                 ...     ...
1495                      1.0              2021.0  2021.0
1496                      0.0              2021.0  2021.0
1497                      0.0              3056.0  2544.0
1498                      0.0              2021.0  2021.0
1499                      0.0              2021.0  2021.0

                                                                ...           \
                                                                ...
               OriginalImagePixelSpacing[x        y]   WEIGHTS  ... Fibrosis
instance names                                                  ...
0                                 0.143000  0.143000  0.925063  ...      0.0
1                                 0.143000  0.143000  0.925063  ...      0.0
2                                 0.171000  0.171000  1.072015  ...      0.0
3                                 0.143000  0.143000  1.072015  ...      0.0
4                                 0.139000  0.139000  0.925063  ...      0.0
...                                    ...       ...       ...  ...      ...
1495                              0.194311  0.194311  0.925063  ...      0.0
1496                              0.194311  0.194311  0.899010  ...      0.0
1497                              0.139000  0.139000  0.925063  ...      0.0
1498                              0.194311  0.194311  0.925063  ...      0.0
1499                              0.194311  0.194311  1.072015  ...      0.0

                                                                              \

               Hernia Infiltration Mass No Finding Nodule Pleural_Thickening
instance names
0                 0.0          0.0  0.0        0.0    0.0                0.0
1                 0.0          1.0  0.0        0.0    0.0                0.0
2                 0.0          0.0  0.0        1.0    0.0                0.0
3                 0.0          0.0  0.0        1.0    0.0                0.0
4                 0.0          1.0  0.0        0.0    0.0                0.0
...               ...          ...  ...        ...    ...                ...
1495              0.0          1.0  0.0        0.0    0.0                0.0
1496              0.0          0.0  0.0        1.0    0.0                0.0
1497              0.0          0.0  0.0        0.0    0.0                0.0
1498              0.0          0.0  0.0        0.0    0.0                0.0
1499              0.0          0.0  0.0        1.0    0.0                0.0

                                      labels

               Pneumonia Pneumothorax
instance names
0                    0.0          0.0    1.0
1                    0.0          0.0    1.0
2                    0.0          0.0    0.0
3                    0.0          0.0    0.0
4                    0.0          0.0    1.0
...                  ...          ...    ...
1495                 0.0          0.0    1.0
1496                 0.0          0.0    0.0
1497                 0.0          0.0    1.0
1498                 0.0          0.0    1.0
1499                 0.0          0.0    0.0

[1500 rows x 29 columns]

In [91]:

from aif360.sklearn.metrics import *


def get_group_metrics(
    y_true,
    y_pred=None,
    prot_attr=None,
    priv_group=1,
    pos_label=1,
    sample_weight=None,
):
    group_metrics = {}
    group_metrics["base_rate"] = base_rate(
        y_true=y_true, pos_label=pos_label, sample_weight=sample_weight
    )
    group_metrics["statistical_parity_difference"] = statistical_parity_difference(
        y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, priv_group=priv_group, pos_label=pos_label, sample_weight=sample_weight
    )
    group_metrics["disparate_impact_ratio"] = disparate_impact_ratio(
        y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, priv_group=priv_group, pos_label=pos_label, sample_weight=sample_weight
    )
    if not y_pred is None:
        group_metrics["equal_opportunity_difference"] = equal_opportunity_difference(
            y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, priv_group=priv_group, pos_label=pos_label, sample_weight=sample_weight
        )
        group_metrics["average_odds_difference"] = average_odds_difference(
            y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, priv_group=priv_group, pos_label=pos_label, sample_weight=sample_weight
        )
        group_metrics["conditional_demographic_disparity"] = conditional_demographic_disparity(
            y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, pos_label=pos_label, sample_weight=sample_weight
        )
        group_metrics["smoothed_edf"] = smoothed_edf(
        y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, pos_label=pos_label, sample_weight=sample_weight
        )
        group_metrics["df_bias_amplification"] = df_bias_amplification(
        y_true=y_true, y_pred=y_pred, prot_attr=prot_attr, pos_label=pos_label, sample_weight=sample_weight
        )
    return group_metrics




ideal_values = {
    "statistical_parity_difference": 0.0,
    "disparate_impact_ratio": 1.0,
    "equal_opportunity_difference": 0.0,
    "average_odds_difference": 0.0,
    "conditional_demographic_disparity": 0.0,
    "smoothed_edf": 1.0,
    "df_bias_amplification": 0.0
}



def check_distance_to_ideal(metrics):
    dist = 0.0
    for metric in ideal_values.keys():
        dist += (ideal_values[metric]-metrics[metric])**2
    return np.sqrt(dist)

def calculate_metrics(csv_name):
    preddf = pd.read_csv("./expe_log/"+csv_name)
    preddf = convert_to_all_numerical(preddf)


    test_df = preddf[preddf["in_train"] == 0]
    preds = test_df["preds"]
    labels= test_df["labels"]
    weights = test_df["WEIGHTS"]


    metrics_after = get_group_metrics(
        y_true=labels,
        y_pred=preds,
        prot_attr=test_df[protected_attribute],
        priv_group=1,
        pos_label=1,
        sample_weight= weights if csv_name=="preds.csv" else None
    )

    
    # Affichage des résultats de fairness
    for metric, value in metrics_after.items():
        print(f"{metric}: {value:.4f}")

    print("Distance to ideal:",check_distance_to_ideal(metrics_after))

    return metrics_after,test_df


# Comparaison des changements dans les métriques
def compare_to_base_preds(metrics_after):
    for metric in metrics_before.keys():
        before = metrics_before[metric]
        after = metrics_after[metric]
        change = after - before
        print(f"{metric}: Avant = {before:.4f}, Après = {after:.4f}, Changement = {change:.4f}")

In [92]:

metrics_before_training = get_group_metrics(
    y_true=preddf['labels'],
    y_pred=None,
    prot_attr=preddf[protected_attribute],
    priv_group=1,
    pos_label=1
)

# Affichage des résultats
for metric, value in metrics_before_training.items():
    print(f"{metric}: {value:.4f}")

base_rate: 0.4607
statistical_parity_difference: -0.1307
disparate_impact_ratio: 0.7430

In [93]:
test_df = preddf[preddf["in_train"] == 0]
preds = test_df["preds"]
labels= test_df["labels"]

metrics_before = get_group_metrics(
    y_true=labels,
    y_pred=preds,
    prot_attr=test_dataset.protected_attributes[:, 0],
    priv_group=1,
    pos_label=1
)

# Affichage des résultats
for metric, value in metrics_before.items():
    print(f"{metric}: {value:.4f}")

base_rate: 0.4827
statistical_parity_difference: -0.0598
disparate_impact_ratio: 0.8369
equal_opportunity_difference: 0.1326
average_odds_difference: 0.0169
conditional_demographic_disparity: -0.0191
smoothed_edf: 0.1746
df_bias_amplification: -0.3485

In [94]:
from aif360.algorithms.preprocessing import Reweighing
from train_classifieur import train_classifier, pred_classifier


# Appliquer Reweighing sur le dataset
rw = Reweighing(unprivileged_groups=[{protected_attribute: unpriviliged_group}], privileged_groups=[{protected_attribute: priviliged_group}])
rw.fit(train_dataset)
transformed_dataset = rw.transform(dataset)


preddf["WEIGHTS"] = transformed_dataset.instance_weights


#On écrits les poids dans les metadatas
csv_df = pd.read_csv(data_dir+"/metadata.csv")
csv_df.iloc[:, -1] = preddf["WEIGHTS"].values
csv_df.to_csv(data_dir+"/metadata.csv", index=False)



""" ckpt_path, ckpt_score = train_classifier(
    logdir="./expe_log/",
    datadir=data_dir,
    csv=data_dir+"/metadata.csv",
)

# Faire des prédictions
pred_classifier(
    datadir=data_dir,
    csv_in=data_dir+"/metadata.csv",
    csv_out="./expe_log/preds.csv",
    ckpt_path=ckpt_path
)  """

' ckpt_path, ckpt_score = train_classifier(\n    logdir="./expe_log/",\n    datadir=data_dir,\n    csv=data_dir+"/metadata.csv",\n)\n\n# Faire des prédictions\npred_classifier(\n    datadir=data_dir,\n    csv_in=data_dir+"/metadata.csv",\n    csv_out="./expe_log/preds.csv",\n    ckpt_path=ckpt_path\n)  '

In [95]:
metrics_after, test_df_reweighing = calculate_metrics("preds.csv")

base_rate: 0.4783
statistical_parity_difference: -0.0310
disparate_impact_ratio: 0.9142
equal_opportunity_difference: 0.1326
average_odds_difference: 0.0169
conditional_demographic_disparity: -0.0099
smoothed_edf: 0.0872
df_bias_amplification: -0.2089
Distance to ideal: 0.9503335130801576

In [96]:
print("\nComparaison des changements dans les métriques :")
compare_to_base_preds(metrics_after)

Comparaison des changements dans les métriques :
base_rate: Avant = 0.4827, Après = 0.4783, Changement = -0.0044
statistical_parity_difference: Avant = -0.0598, Après = -0.0310, Changement = 0.0289
disparate_impact_ratio: Avant = 0.8369, Après = 0.9142, Changement = 0.0773
equal_opportunity_difference: Avant = 0.1326, Après = 0.1326, Changement = 0.0000
average_odds_difference: Avant = 0.0169, Après = 0.0169, Changement = -0.0000
conditional_demographic_disparity: Avant = -0.0191, Après = -0.0099, Changement = 0.0092
smoothed_edf: Avant = 0.1746, Après = 0.0872, Changement = -0.0874
df_bias_amplification: Avant = -0.3485, Après = -0.2089, Changement = 0.1396

## Disparate Impact Remover:

In [97]:
from aif360.algorithms.preprocessing import DisparateImpactRemover
import pandas as pd

def apply_disparate_impact_remover(train_dataset, repair_level=1.0):
    dir = DisparateImpactRemover(sensitive_attribute=protected_attribute,repair_level=repair_level)
    train_dataset.instance_names = original_df[["Patient ID", "Follow-up #"]].values.tolist()
    repaired_dataset = dir.fit_transform(train_dataset)
    
    
    repaired_df = pd.DataFrame(
        data=repaired_dataset.features,
        columns=repaired_dataset.feature_names
    )
    repaired_df['label'] = repaired_dataset.labels
    repaired_df[["Patient ID", "Follow-up #"]] = pd.DataFrame(repaired_dataset.instance_names, columns=["Patient ID", "Follow-up #"])
    
    merged_df = pd.merge(
        repaired_df,
        original_df[["Patient ID", "Follow-up #", "Image Index"]],
        on=["Patient ID", "Follow-up #"],
        how="inner"
    )
    return merged_df.drop(columns=[x for x in merged_df if x not in original_columns+[protected_attribute, "in_train"]])


repaired_train_df = apply_disparate_impact_remover(train_dataset)
repaired_test_df =  apply_disparate_impact_remover(test_dataset)
repaired_df = pd.concat([repaired_train_df, repaired_test_df], ignore_index=True)

In [98]:
repaired_df.to_csv(data_dir+"/repaired_metadata.csv", index=False)

# Entraîner le modèle avec les poids ajustés
""" ckpt_path, ckpt_score = train_classifier(
    logdir="./expe_log/",
    datadir=data_dir,
    csv=data_dir+"/repaired_metadata.csv",
)

# Faire des prédictions
pred_classifier(
    datadir=data_dir,
    csv_in=data_dir+"/repaired_metadata.csv",
    csv_out="./expe_log/repaired_preds.csv",
    ckpt_path=ckpt_path
)  """

' ckpt_path, ckpt_score = train_classifier(\n    logdir="./expe_log/",\n    datadir=data_dir,\n    csv=data_dir+"/repaired_metadata.csv",\n)\n\n# Faire des prédictions\npred_classifier(\n    datadir=data_dir,\n    csv_in=data_dir+"/repaired_metadata.csv",\n    csv_out="./expe_log/repaired_preds.csv",\n    ckpt_path=ckpt_path\n)  '

In [99]:
metrics_after,test_df_dir = calculate_metrics("repaired_preds.csv")

base_rate: 0.4934
statistical_parity_difference: 0.0133
disparate_impact_ratio: 1.0205
equal_opportunity_difference: -0.0591
average_odds_difference: -0.0198
conditional_demographic_disparity: 0.0033
smoothed_edf: 0.0374
df_bias_amplification: -0.1862
Distance to ideal: 0.9827058971507231

In [100]:
compare_to_base_preds(metrics_after)

base_rate: Avant = 0.4827, Après = 0.4934, Changement = 0.0108
statistical_parity_difference: Avant = -0.0598, Après = 0.0133, Changement = 0.0732
disparate_impact_ratio: Avant = 0.8369, Après = 1.0205, Changement = 0.1836
equal_opportunity_difference: Avant = 0.1326, Après = -0.0591, Changement = -0.1917
average_odds_difference: Avant = 0.0169, Après = -0.0198, Changement = -0.0367
conditional_demographic_disparity: Avant = -0.0191, Après = 0.0033, Changement = 0.0224
smoothed_edf: Avant = 0.1746, Après = 0.0374, Changement = -0.1372
df_bias_amplification: Avant = -0.3485, Après = -0.1862, Changement = 0.1623

## LFR

In [101]:
from aif360.algorithms.preprocessing.lfr import LFR
unp_grp = [{protected_attribute: 0}]
pr_grp = [{protected_attribute: 1}]
TR = LFR(
            unprivileged_groups=unp_grp,
            privileged_groups=pr_grp,
            k=5,
            Ax=0.01,
            Ay=1.0,
            Az=50.0,
            print_interval=500,
            verbose=1,
            seed=None,
        )
TR = TR.fit(train_dataset, maxiter=5000, maxfun=5000)
lfr_train = TR.transform(train_dataset)
lfr_test = TR.transform(test_dataset)
preproc = TR

step: 0, loss: 240029.36011954112, L_x: 24002842.61561454,  L_y: 0.7963616476126226,  L_z: 0.0027520349620993923
step: 500, loss: 239891.38155847185, L_x: 23989049.800907493,  L_y: 0.6936953083994055,  L_z: 0.0037970817699320967
step: 1000, loss: 239240.9334574784, L_x: 23924022.21474602,  L_y: 0.7109956661480301,  L_z: 6.287040300516105e-06
step: 1500, loss: 235607.0301883398, L_x: 23558733.233348705,  L_y: 19.697854852751174,  L_z: 5.520148102077046e-17
step: 2000, loss: 225489.24920285633, L_x: 22548852.483800262,  L_y: 0.7243648537110089,  L_z: 4.53255157582613e-36
step: 2500, loss: 28651.30199138042, L_x: 2863492.8944935063,  L_y: 14.904411156590054,  L_z: 0.0293727057753669
step: 3000, loss: 45822.00612366975, L_x: 4581987.800413704,  L_y: 1.0063990619711365,  L_z: 0.022434409414813235
step: 3500, loss: 43840.49811541176, L_x: 4383765.024868793,  L_y: 0.9673970876869393,  L_z: 0.037609392722744564
step: 4000, loss: 19232.26076933844, L_x: 1922980.6639634857,  L_y: 0.7015384915313733,  L_z: 0.03505182424105208
step: 4500, loss: 21277.38784166629, L_x: 2125591.37068138,  L_y: 19.703863852717376,  L_z: 0.035405419995429774
step: 5000, loss: 12071.371666103698, L_x: 1206883.881960092,  L_y: 0.7807279947408052,  L_z: 0.0350423701607003
step: 5500, loss: 12025.274199863221, L_x: 1202265.4581069723,  L_y: 0.8675001739242282,  L_z: 0.03504237239146536

In [102]:
def safe_convert_to_dataframe(dataset):
    # Extract features, labels, and protected attributes
    features = dataset.features
    labels = dataset.labels
    protected_attributes = dataset.protected_attributes

    # Combine them into a DataFrame
    df = pd.DataFrame(features, columns=dataset.feature_names)
    df['label'] = labels
    for i, attr_name in enumerate(dataset.protected_attribute_names):
        df[attr_name] = protected_attributes[:, i]

    return df

lfr_train_df = safe_convert_to_dataframe(train_dataset)
lfr_test_df = safe_convert_to_dataframe(test_dataset)
lfr_df = pd.concat([lfr_train_df, lfr_test_df], ignore_index=True)
lfr_df= pd.merge(
    lfr_df,
    original_df[["Follow-up #", "Patient ID", "Image Index"]],
    on=["Follow-up #", "Patient ID"],
    how="left"  # Use "left" to keep all rows from lfr_df
)

In [103]:
lfr_df.to_csv(data_dir+"/lfr_metadata.csv", index=False)
""" ckpt_path, ckpt_score = train_classifier(
    logdir="./expe_log/",
    datadir=data_dir,
    csv=data_dir+"/lfr_metadata.csv",
)

# Faire des prédictions
pred_classifier(
    datadir=data_dir,
    csv_in=data_dir+"/lfr_metadata.csv",
    csv_out="./expe_log/lfr_preds.csv",
    ckpt_path=ckpt_path
)  """

' ckpt_path, ckpt_score = train_classifier(\n    logdir="./expe_log/",\n    datadir=data_dir,\n    csv=data_dir+"/lfr_metadata.csv",\n)\n\n# Faire des prédictions\npred_classifier(\n    datadir=data_dir,\n    csv_in=data_dir+"/lfr_metadata.csv",\n    csv_out="./expe_log/lfr_preds.csv",\n    ckpt_path=ckpt_path\n)  '

In [104]:
metrics_after, test_df_lfr=calculate_metrics("lfr_preds.csv")

base_rate: 0.4827
statistical_parity_difference: -0.1760
disparate_impact_ratio: 0.6102
equal_opportunity_difference: 0.0296
average_odds_difference: -0.0981
conditional_demographic_disparity: -0.0534
smoothed_edf: 0.4880
df_bias_amplification: -0.0351
Distance to ideal: 0.6779582968574077

In [105]:
compare_to_base_preds(metrics_after)

base_rate: Avant = 0.4827, Après = 0.4827, Changement = 0.0000
statistical_parity_difference: Avant = -0.0598, Après = -0.1760, Changement = -0.1162
disparate_impact_ratio: Avant = 0.8369, Après = 0.6102, Changement = -0.2267
equal_opportunity_difference: Avant = 0.1326, Après = 0.0296, Changement = -0.1029
average_odds_difference: Avant = 0.0169, Après = -0.0981, Changement = -0.1150
conditional_demographic_disparity: Avant = -0.0191, Après = -0.0534, Changement = -0.0343
smoothed_edf: Avant = 0.1746, Après = 0.4880, Changement = 0.3134
df_bias_amplification: Avant = -0.3485, Après = -0.0351, Changement = 0.3134

# Post Proc

In [106]:
from aif360.algorithms.postprocessing.reject_option_classification import RejectOptionClassification

# Define privileged and unprivileged groups as dictionaries
unprivileged_groups = [{protected_attribute: unpriviliged_group}]
privileged_groups = [{protected_attribute: priviliged_group}]

metric_name = "Statistical parity difference"
metric_ub = 0.5
metric_lb = -0.5




def apply_ROC_to_preds(test_df, weights=False):
    ROC = RejectOptionClassification(
        unprivileged_groups=unprivileged_groups,
        privileged_groups=privileged_groups,
        low_class_thresh=0.0001,
        high_class_thresh=0.999,
        num_class_thresh=100,
        num_ROC_margin=50,
        metric_name=metric_name,
        metric_ub=metric_ub,
        metric_lb=metric_lb
    )

    test_dt = test_dataset.copy()

    test_dt.labels = test_df["preds"]

    ROC = ROC.fit(test_dataset, test_dt)
    df_roc_val_pred = ROC.predict(test_dt)
    post_proc_metrics=get_group_metrics(
        y_true=test_dataset.labels[:,0],
        y_pred=df_roc_val_pred .labels[:,0],
        prot_attr=test_dt.protected_attributes[:, 0],
        pos_label=1,
        sample_weight=test_dt.features[:, test_dt.feature_names.index('WEIGHTS')] if weights else None ,
    )
    return post_proc_metrics

In [107]:
apply_ROC_to_preds(test_df_reweighing, weights=True)

{'base_rate': np.float64(0.4782672526762588),
 'statistical_parity_difference': np.float64(-0.13524793831965026),
 'disparate_impact_ratio': 0.7418463863603171,
 'equal_opportunity_difference': 0.0,
 'average_odds_difference': 0.0,
 'conditional_demographic_disparity': np.float64(-0.03939888618391865),
 'smoothed_edf': np.float64(0.2961567705890956),
 'df_bias_amplification': np.float64(0.0)}

In [108]:
apply_ROC_to_preds(test_df_dir)

{'base_rate': np.float64(0.4826666666666667),
 'statistical_parity_difference': np.float64(-0.22977520955041902),
 'disparate_impact_ratio': 0.5900413527445761,
 'equal_opportunity_difference': 0.0,
 'average_odds_difference': 0.0,
 'conditional_demographic_disparity': np.float64(-0.06650164226993983),
 'smoothed_edf': np.float64(0.5231378927859587),
 'df_bias_amplification': np.float64(0.0)}

In [109]:
apply_ROC_to_preds(test_df_lfr)

{'base_rate': np.float64(0.4826666666666667),
 'statistical_parity_difference': np.float64(-0.22977520955041902),
 'disparate_impact_ratio': 0.5900413527445761,
 'equal_opportunity_difference': 0.0,
 'average_odds_difference': 0.0,
 'conditional_demographic_disparity': np.float64(-0.06650164226993983),
 'smoothed_edf': np.float64(0.5231378927859587),
 'df_bias_amplification': np.float64(0.0)}

In [110]:
def cross_validate_ROC(test_df, metrics_to_try=None, class_thresholds=None, fairness_bounds=None, weights=False):
    if metrics_to_try is None:
        metrics_to_try = [
            "Statistical parity difference",
            "Equal opportunity difference",
            "Average odds difference"
        ]
    
    if class_thresholds is None:
        class_thresholds = [(0.001, 0.999)]  # Reduced to one default threshold pair
    
    if fairness_bounds is None:
        fairness_bounds = [
            (-0.01, 0.01),
            (-0.05, 0.05),
            (-0.1, 0.1),
            (-0.25, 0.25)
        ]
    
    results_dfs = {}
    
    for metric in metrics_to_try:
        metric_results = []
        
        for low_thresh, high_thresh in class_thresholds:
            for lb, ub in fairness_bounds:
                try:
                    ROC = RejectOptionClassification(
                        unprivileged_groups=unprivileged_groups,
                        privileged_groups=privileged_groups,
                        low_class_thresh=low_thresh,
                        high_class_thresh=high_thresh,
                        num_class_thresh=100,
                        num_ROC_margin=50,
                        metric_name=metric,
                        metric_ub=ub,
                        metric_lb=lb
                    )

                    test_dt = test_dataset.copy()
                    test_dt.labels = test_dt.labels = test_df["preds"].values.reshape(-1, 1)

                    ROC = ROC.fit(test_dataset, test_dt)
                    df_roc_val_pred = ROC.predict(test_dt)
                    
                    metrics = get_group_metrics(
                        y_true=test_dataset.labels[:,0],
                        y_pred=df_roc_val_pred.labels[:,0],
                        prot_attr=test_dt.protected_attributes[:, 0],
                        pos_label=1,
                        sample_weight=test_dt.features[:, test_dt.feature_names.index('WEIGHTS')] if weights else None
                    )
                    
                    distance = check_distance_to_ideal(metrics)
                    result_row = {
                        'low_class_thresh': low_thresh,
                        'high_class_thresh': high_thresh,
                        'metric_lb': lb,
                        'metric_ub': ub,
                        'distance': distance,
                        **metrics
                    }
                    metric_results.append(result_row)
                        
                except Exception as e:
                    result_row = {
                        'low_class_thresh': low_thresh,
                        'high_class_thresh': high_thresh,
                        'metric_lb': lb,
                        'metric_ub': ub,
                        'distance': np.nan,
                        'error': str(e)
                    }
                    metric_results.append(result_row)
        
        df = pd.DataFrame(metric_results)
        df.set_index(['low_class_thresh', 'high_class_thresh', 'metric_lb', 'metric_ub'], inplace=True)
        results_dfs[metric] = df
    
    return results_dfs
results_dfs = cross_validate_ROC(test_df_dir)

/home/rayan/Documents/Fairness/projet/myenv/lib/python3.11/site-packages/aif360/algorithms/postprocessing/reject_option_classification.py:160: UserWarning:

Unable to satisy fairness constraints

/home/rayan/Documents/Fairness/projet/myenv/lib/python3.11/site-packages/aif360/algorithms/postprocessing/reject_option_classification.py:160: UserWarning:

Unable to satisy fairness constraints

/home/rayan/Documents/Fairness/projet/myenv/lib/python3.11/site-packages/aif360/algorithms/postprocessing/reject_option_classification.py:160: UserWarning:

Unable to satisy fairness constraints

In [111]:
results_dfs["Statistical parity difference"]

                                                        distance  base_rate  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01       0.672817   0.482667
                                   -0.05     0.05       0.672817   0.482667
                                   -0.10     0.10       0.672817   0.482667
                                   -0.25     0.25       0.672817   0.482667

                                                        statistical_parity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           -0.229775
                                   -0.05     0.05                           -0.229775
                                   -0.10     0.10                           -0.229775
                                   -0.25     0.25                           -0.229775

                                                        disparate_impact_ratio  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                     0.590041
                                   -0.05     0.05                     0.590041
                                   -0.10     0.10                     0.590041
                                   -0.25     0.25                     0.590041

                                                        equal_opportunity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                                0.0
                                   -0.05     0.05                                0.0
                                   -0.10     0.10                                0.0
                                   -0.25     0.25                                0.0

                                                        average_odds_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           0.0
                                   -0.05     0.05                           0.0
                                   -0.10     0.10                           0.0
                                   -0.25     0.25                           0.0

                                                        conditional_demographic_disparity  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                               -0.066502
                                   -0.05     0.05                               -0.066502
                                   -0.10     0.10                               -0.066502
                                   -0.25     0.25                               -0.066502

                                                        smoothed_edf  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01           0.523138
                                   -0.05     0.05           0.523138
                                   -0.10     0.10           0.523138
                                   -0.25     0.25           0.523138

                                                        df_bias_amplification
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                         0.0
                                   -0.05     0.05                         0.0
                                   -0.10     0.10                         0.0
                                   -0.25     0.25                         0.0

In [112]:
results_dfs["Equal opportunity difference"]

                                                        distance  base_rate  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01       0.672817   0.482667
                                   -0.05     0.05       0.672817   0.482667
                                   -0.10     0.10       0.672817   0.482667
                                   -0.25     0.25       0.672817   0.482667

                                                        statistical_parity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           -0.229775
                                   -0.05     0.05                           -0.229775
                                   -0.10     0.10                           -0.229775
                                   -0.25     0.25                           -0.229775

                                                        disparate_impact_ratio  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                     0.590041
                                   -0.05     0.05                     0.590041
                                   -0.10     0.10                     0.590041
                                   -0.25     0.25                     0.590041

                                                        equal_opportunity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                                0.0
                                   -0.05     0.05                                0.0
                                   -0.10     0.10                                0.0
                                   -0.25     0.25                                0.0

                                                        average_odds_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           0.0
                                   -0.05     0.05                           0.0
                                   -0.10     0.10                           0.0
                                   -0.25     0.25                           0.0

                                                        conditional_demographic_disparity  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                               -0.066502
                                   -0.05     0.05                               -0.066502
                                   -0.10     0.10                               -0.066502
                                   -0.25     0.25                               -0.066502

                                                        smoothed_edf  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01           0.523138
                                   -0.05     0.05           0.523138
                                   -0.10     0.10           0.523138
                                   -0.25     0.25           0.523138

                                                        df_bias_amplification
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                         0.0
                                   -0.05     0.05                         0.0
                                   -0.10     0.10                         0.0
                                   -0.25     0.25                         0.0

In [113]:
results_dfs["Average odds difference"]

                                                        distance  base_rate  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01       0.672817   0.482667
                                   -0.05     0.05       0.672817   0.482667
                                   -0.10     0.10       0.672817   0.482667
                                   -0.25     0.25       0.672817   0.482667

                                                        statistical_parity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           -0.229775
                                   -0.05     0.05                           -0.229775
                                   -0.10     0.10                           -0.229775
                                   -0.25     0.25                           -0.229775

                                                        disparate_impact_ratio  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                     0.590041
                                   -0.05     0.05                     0.590041
                                   -0.10     0.10                     0.590041
                                   -0.25     0.25                     0.590041

                                                        equal_opportunity_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                                0.0
                                   -0.05     0.05                                0.0
                                   -0.10     0.10                                0.0
                                   -0.25     0.25                                0.0

                                                        average_odds_difference  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                           0.0
                                   -0.05     0.05                           0.0
                                   -0.10     0.10                           0.0
                                   -0.25     0.25                           0.0

                                                        conditional_demographic_disparity  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                               -0.066502
                                   -0.05     0.05                               -0.066502
                                   -0.10     0.10                               -0.066502
                                   -0.25     0.25                               -0.066502

                                                        smoothed_edf  \
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01           0.523138
                                   -0.05     0.05           0.523138
                                   -0.10     0.10           0.523138
                                   -0.25     0.25           0.523138

                                                        df_bias_amplification
low_class_thresh high_class_thresh metric_lb metric_ub
0.001            0.999             -0.01     0.01                         0.0
                                   -0.05     0.05                         0.0
                                   -0.10     0.10                         0.0
                                   -0.25     0.25                         0.0